let courseList = [
    "Mario Kart Stadium (Mushroom Cup)",
    "Water Park (Mushroom Cup)",
    "Sweet Sweet Canyon (Mushroom Cup)",
    "Thwomp Ruins (Mushroom Cup)",
    "Mario Circuit (Flower Cup)",
    "Toad Harbor (Flower Cup)",
    "Twisted Mansion (Flower Cup)",
    "Shy Guy Falls (Flower Cup)",
    "Sunshine Airport (Star Cup)",
    "Dolphin Shoals (Star Cup)",
    "Electrodome (Star Cup)",
    "Mount Wario (Star Cup)",
    "Cloudtop Cruise (Special Cup)",
    "Bone-Dry Dunes (Special Cup)",
    "Bowser's Castle (Special Cup)",
    "Rainbow Road (Special Cup)",
    "Yoshi Circuit (Egg Cup)",
    "Excitebike Arena (Egg Cup)",
    "Dragon Driftway (Egg Cup)",
    "Mute City (Egg Cup)",
    "Baby Park (Crossing Cup)",
    "Cheese Land (Crossing Cup)",
    "Wild Woods (Crossing Cup)",
    "Animal Crossing (Crossing Cup)",
    "Moo Moo Meadows (Shell Cup)",
    "Mario Circuit GBA (Shell Cup)",
    "Cheep Cheep Beach (Shell Cup)",
    "Toad's Turnpike (Shell Cup)",
    "Dry Dry Desert (Banana Cup)",
    "Donut Plains 3 (Banana Cup)",
    "Royal Raceway (Banana Cup)",
    "DK Jungle (Banana Cup)",
    "Wario Stadium (Leaf Cup)",
    "Sherbet Land (Leaf Cup)",
    "Music Park (Leaf Cup)",
    "Yoshi Valley (Leaf Cup)",
    "Tick-Tock Clock (Lightning Cup)",
    "Piranha Plant Slide (Lightning Cup)",
    "Grumble Volcano (Lightning Cup)",
    "Rainbow Road N64 (Lightning Cup)",
    "Wario's Goldmine (Triforce Cup)",
    "Rainbow Road SNES (Triforce Cup)",
    "Ice Ice Outpost (Triforce Cup)",
    "Hyrule Circuit (Triforce Cup)",
    "Neo Bowser City (Bell Cup)",
    "Ribbon Road (Bell Cup)",
    "Super Bell Subway (Bell Cup)",
    "Big Blue (Bell Cup)",
    "Paris Promenade (Golden Dash Cup)",
    "Toad Circuit (Golden Dash Cup)",
    "Choco Mountain (Golden Dash Cup)",
    "Coconut Mall (Golden Dash Cup)",
    "Tokyo Blur (Lucky Cat Cup)",
    "Shroom Ridge (Lucky Cat Cup)",
    "Sky Garden (Lucky Cat Cup)",
    "Ninja Hideaway (Lucky Cat Cup)",
    "New York Minute (Turnip Cup)",
    "Mario Circuit 3 SNES (Turnip Cup)",
    "Kalimari Desert (Turnip Cup)",
    "Waluigi Pinball (Turnip Cup)",
    "Sydney Sprint (Propeller Cup)",
    "Snow Land (Propeller Cup)",
    "Mushroom Gorge (Propeller Cup)",
    "Sky-High Sundae (Propeller Cup)",
    "London Loop (Rock Cup)",
    "Boo Lake (Rock Cup)",
    "Rock Rock Mountain (Rock Cup)",
    "Maple Treeway (Rock Cup)",
    "Berlin Byways (Moon Cup)",
    "Peach Gardens (Moon Cup)",
    "Merry Mountain (Moon Cup)",
    "Rainbow Road 3DS (Moon Cup)",
    "Amsterdam Drift (Fruit Cup)",
    "Riverside Park (Fruit Cup)",
    "DK Summit (Fruit Cup)",
    "Yoshi's Island (Fruit Cup)",
    "Bangkok Rush (Boomerang Cup)",
    "Mario Circuit DS (Boomerang Cup)",
    "Waluigi Stadium (Boomerang Cup)",
    "Singapore Speedway (Boomerang Cup)",
    "Athens Dash (Feather Cup)",
    "Daisy Cruiser (Feather Cup)",
    "Moonview Highway (Feather Cup)",
    "Squeaky Clean Sprint (Feather Cup)",
    "Los Angeles Laps (Cherry Cup)",
    "Sunset Wilds (Cherry Cup)",
    "Koopa Cape (Cherry Cup)",
    "Vancouver Velocity (Cherry Cup)",
]

export default courseList